version: '3.8'

services:
  wordpress:
    build:
      context: . # This assumes the Dockerfile is in the same directory
      dockerfile: Dockerfile # Specify the name of your Dockerfile
    restart: unless-stopped
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_pass
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: 'wp_'
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
      interval: 10s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '2G'
        reservations:
          cpus: '2.0'
          memory: '2G'

  db:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress_pass
      MARIADB_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-uroot', '-proot_password']
      interval: 10s
      timeout: 30s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1G'
        reservations:
          cpus: '0.25'
          memory: '256M'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress_pass
      UPLOAD_LIMIT: 1GB
    ports:
      - '8080:80'
    depends_on:
      db:
        condition: service_healthy

volumes:
  wordpress_data:
  db_data:
  redis_data:
